version: '3.1'
services:
    nginx:
        image: nginx:alpine
        working_dir: /var/www/
        ports:
            - "8000:80"
        volumes:
            - ./html:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - db
    db:
        container_name: db
        image: mariadb:10.3.39-focal
        volumes:
            - ./data:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: Devanon1
            MYSQL_DATABASE: drupal
            MYSQL_USER: fabricio
            MYSQL_PASSWORD: Devanon1
        ports:
            - "2000:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
        depends_on:
            - db
        ports:
            - "1000:80"
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - ./html:/var/www



    # php-nginx-environment:
    #     container_name: php-nginx
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     volumes:
    #         - ./html:/usr/share/nginx/html/
    #     depends_on:
    #         - db
    #     ports:
    #         - "8000:80"

    
    
