version: '3.1'
services:
    ambiente_nginx:
        image: nginx:alpine
        working_dir: /var/www/
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - ambiente_db
    ambiente_db:
        container_name: ambiente_db
        image: mariadb:10.3.39-focal
        volumes:
            - ./data:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: Devanon1
            MYSQL_DATABASE: database
            MYSQL_USER: fabricio
            MYSQL_PASSWORD: Devanon1
        ports:
            - "2000:3306"
    ambiente_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: ambiente_db
        depends_on:
            - ambiente_db
        ports:
            - "1000:80"
    ambiente_php:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www



    # php-nginx-environment:
    #     container_name: php-nginx
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     volumes:
    #         - ./html:/usr/share/nginx/html/
    #     depends_on:
    #         - db
    #     ports:
    #         - "8000:80"

    
    
